#!/bin/bash
DIRNAME=/tmp/firsta
echo $PWD
#ls ../first/first
F1=$(ls $DIRNAME|head -1)
F2=${F1//[0-9]/}
F3=${F2::-4}
FILENUM=$(ls -1 $DIRNAME | wc -l)
TRUENUM=0
#echo $F1
#echo $F2
#echo $F3
#cat $DIRNAME/${F3}1.log
for i in $(seq 1 $FILENUM); do
        if [ $(cat $DIRNAME/$F3$i.log) = 'true' ]; then
          TRUENUM=$(($TRUENUM+1))
                if [ $TRUENUM = 2 ]; then break 2 
                fi
         fi
done 
echo "Got $TRUENUM 'true', $i was final"
