#!/bin/bash
JO=/tmp
JOB=firsta
arr=(true false)
echo "$JO/$JOB/1.log"

if [ -d "$JO/$JOB" ]; then
  echo "exist"
else
mkdir $JO/$JOB
fi

for i in `seq 1 50`; do
touch $JO/$JOB/$JOB$i.log
echo ${arr[$(( ( RANDOM % 1 )  + 0 ))]} > $JO/$JOB/$JOB$i.log
done
