ENV["LC_ALL"] = "en_US.UTF-8"
BOX_IMAGE = "generic/centos7"
NODE_COUNT = "1".to_i
NETWORK_BASE = "192.168.101"
NETWORK_NETMASK = "255.255.255.0"
INTEGRATION_START_SEGMENT = 10

Vagrant.configure("2") do |config|
	(1..NODE_COUNT).each do |i|
	  config.vm.define "node#{i}" do |rev|
            rev.vm.box = BOX_IMAGE 
	    rev.vm.hostname = "node#{i}.box"
	    rev.vm.network "private_network", ip: "#{NETWORK_BASE}.#{INTEGRATION_START_SEGMENT + i}", netmask: NETWORK_NETMASK
	    rev.vm.provision "shell", inline: $script_rev#{i}
	    rev.vm.provision "shell", inline: "echo node#{i} is up and running && ifconfig | grep 'inet 192.168'"
	end
  
end
$script_rev1 = <<-EOF2
export LC_ALL=en_US.UTF-8
sudo iptables -I INPUT -j ACCEPT
sudo setsebool -P httpd_can_network_connect true && echo SELinux command OK
EOF2
end
