---
- name: Clean www dir
  file:
    state: absent
    path: "/var/www"

- name: make www dir
  file:
    state: directory
    path: "/var/www/html"

- name: install nginx
  apt: 
    update_cache: yes 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - nginx

- name: Template nginx file 
  template:
    src: ../templates/nginx.j2
    dest: /etc/nginx/conf.d/default.conf

- name: restart nginx
  command: "nginx -s reload"
