---
- name: Create new user
    user:
      name: "{{ item }}"
         state: present
         generate_ssh_key: yes
         ssh_key_bits: 2048
         ssh_key_file: .ssh/id_rsa
      with_items: "{{ users }}"
