---
- name: Roles for DB/Jenkins node
  hosts: db_jenkins
  roles:
    - git
    - maven
    - mysql
    - jenkins
- name: Roles for Loadbalancer node
  hosts: loadbalancer
  roles:
    - nginx
- name: Roles for Backend node
  hosts: backend
  roles:
    - tomcat
