---
- name: apply common configuration to all nodes
  hosts: all
  roles:
    - common

- name: configure and deploy the front- and backend servers and application code
  hosts: frontend,backend
  vars:
    php_enable_php_fpm: true
    apache_vhosts:
      - servername: "www.example.com"
        documentroot: "/var/www/example"
        extra_parameters: |
              ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:4444/var/www/example"
  roles:
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.apache-php-fpm  
  tasks:
  - name: install debs
    apt: name={{item}}
    with_items:
    - nginx
    - php5-fpm

- name: deploy MySQL and configure the databases
  hosts: redis
  remote_user: root
  tasks:
  - name: install debs
    apt: name={{item}}
    with_items:
    - redis
